<a href="https://colab.research.google.com/github/Madhavi-1234/pytorch-from-scratch/blob/main/Pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_breast_cancer



In [45]:
data= load_breast_cancer()

In [46]:
df= pd.DataFrame(data.data, columns= data.feature_names)

In [47]:
df['target'] = data.target

In [48]:
x=df.drop('target', axis=1)


In [49]:
y= df['target']

In [50]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [51]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2,random_state= 42)

## Scaling

In [52]:
scaler= StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.fit_transform(x_test)

In [53]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [54]:
y_train

68     1
181    0
63     1
248    1
60     1
      ..
71     1
106    1
270    1
435    0
102    1
Name: target, Length: 455, dtype: int64

In [55]:
# lable encoding
# id data is in character or alphabet form
encoder= LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.fit_transform(y_test)

In [56]:
y_train

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,

In [57]:
x_train_tensor= torch.from_numpy(x_train)
x_test_tensor= torch.from_numpy(x_test)
y_train_tensor= torch.from_numpy(y_train)
y_test_tensor= torch.from_numpy(y_test)

In [58]:
x_train_tensor.shape

torch.Size([455, 30])

In [59]:
y_train_tensor.shape

torch.Size([455])

In [60]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [61]:
y_test_tensor

tensor([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0])

# Defining a Model

In [62]:
import torch

class MySimpleNN():

    def __init__(self, x):
        self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, x):
        z = torch.matmul(x, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # calculate loss
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss




Important Parameters

In [63]:
learning_rate= 0.1
epochs= 25

# Training Pipeline

In [64]:
# create model
model= MySimpleNN(x_train_tensor)


# define loop
for epoch in range(epochs):

   # forward pass
  y_pred= model.forward(x_train_tensor)
   #print(y_pred)


  #loss calcualte
  loss= model.loss_function(y_pred, y_train_tensor)
  print(f"Epoch:{epoch + 1}, loss:{loss.item()}")


  # backward pass
  loss.backward()

  # parametrs update
  with torch.no_grad():
   model.weights-= learning_rate * model.weights.grad
   model.bias-= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loass in each epoch
  print(f" Epoch: { epoch+ 1}, Loss: {loss.item()}")

Epoch:1, loss:3.513844764939515
 Epoch: 1, Loss: 3.513844764939515
Epoch:2, loss:3.3462335315139344
 Epoch: 2, Loss: 3.3462335315139344
Epoch:3, loss:3.176630660360957
 Epoch: 3, Loss: 3.176630660360957
Epoch:4, loss:3.0042806084643203
 Epoch: 4, Loss: 3.0042806084643203
Epoch:5, loss:2.8323708268366694
 Epoch: 5, Loss: 2.8323708268366694
Epoch:6, loss:2.6600208629976216
 Epoch: 6, Loss: 2.6600208629976216
Epoch:7, loss:2.4841311522222917
 Epoch: 7, Loss: 2.4841311522222917
Epoch:8, loss:2.311909727489639
 Epoch: 8, Loss: 2.311909727489639
Epoch:9, loss:2.143332586936461
 Epoch: 9, Loss: 2.143332586936461
Epoch:10, loss:1.9768617217844076
 Epoch: 10, Loss: 1.9768617217844076
Epoch:11, loss:1.8146371534746084
 Epoch: 11, Loss: 1.8146371534746084
Epoch:12, loss:1.6573343069201325
 Epoch: 12, Loss: 1.6573343069201325
Epoch:13, loss:1.5076308844066049
 Epoch: 13, Loss: 1.5076308844066049
Epoch:14, loss:1.3713793286335052
 Epoch: 14, Loss: 1.3713793286335052
Epoch:15, loss:1.250139846040099

In [65]:
model.weights

tensor([[-0.1570],
        [-0.1866],
        [-0.2111],
        [ 0.5627],
        [-0.1981],
        [ 0.2566],
        [-0.5430],
        [ 0.3969],
        [-0.0547],
        [ 0.0375],
        [-0.3066],
        [ 0.2033],
        [ 0.1564],
        [-0.1095],
        [-0.0716],
        [-0.0540],
        [-0.1282],
        [ 0.3721],
        [ 0.5541],
        [ 0.3524],
        [-0.0977],
        [ 0.3736],
        [-0.2125],
        [ 0.3913],
        [ 0.0038],
        [ 0.0969],
        [-0.3028],
        [-0.3214],
        [ 0.0512],
        [ 0.4086]], dtype=torch.float64, requires_grad=True)

In [66]:
model.bias

tensor([0.3791], dtype=torch.float64, requires_grad=True)

# Evaluation

In [77]:
# model evaluation
with torch.no_grad():
  y_pred= model.forward(x_test_tensor)
  y_pred= (y_pred> 0.5).float()
  accuracy= (y_pred == y_test_tensor).float().mean()
  print(f"'Accuracy':{accuracy.item()}")





'Accuracy':0.5344721674919128
