<a href="https://colab.research.google.com/github/Madhavi-1234/pytorch-from-scratch/blob/main/Pytorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_breast_cancer
import torch.nn as nn



In [4]:
data= load_breast_cancer()

In [5]:
df= pd.DataFrame(data.data, columns= data.feature_names)

In [6]:
df['target'] = data.target

In [7]:
x=df.drop('target', axis=1)


In [8]:
y= df['target']

In [9]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [11]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2,random_state= 42)

## Scaling

In [39]:
scaler= StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.fit_transform(x_test)

In [13]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [14]:
y_train

68     1
181    0
63     1
248    1
60     1
      ..
71     1
106    1
270    1
435    0
102    1
Name: target, Length: 455, dtype: int64

In [38]:
# lable encoding
# id data is in character or alphabet form
encoder= LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.fit_transform(y_test)

In [16]:
y_train

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,

In [40]:
x_train_tensor= torch.from_numpy(x_train)
x_test_tensor= torch.from_numpy(x_test)
y_train_tensor= torch.from_numpy(y_train)
y_test_tensor= torch.from_numpy(y_test)

In [41]:
x_train_tensor.shape

torch.Size([455, 30])

In [19]:
y_train_tensor.shape

torch.Size([455])

In [47]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [31]:
y_test_tensor

tensor([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0])

In [63]:
x_train_tensor = x_train_tensor.float()
y_train_tensor = y_train_tensor.float()


# Defining a Model

In [68]:
import torch
import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out



Important Parameters

In [53]:
learning_rate= 0.1
epochs= 25

In [73]:
loss_fn= nn.BCELoss()


# Training Pipeline

In [81]:
# create model
model= MySimpleNN(x_train_tensor.shape[1])

# define the optimizer
optimizer= torch.optim.SGD(model.parameters(), lr= learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred= model(x_train_tensor)

  #loss calcualte
  loss= loss_fn(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parametrs update
  optimizer.step()

  # print loass in each epoch
  print(f" Epoch: { epoch+ 1}, Loss: {loss.item()}")

 Epoch: 1, Loss: 1.062781810760498
 Epoch: 2, Loss: 0.7442108392715454
 Epoch: 3, Loss: 0.5687639713287354
 Epoch: 4, Loss: 0.4719015955924988
 Epoch: 5, Loss: 0.410635769367218
 Epoch: 6, Loss: 0.3678714632987976
 Epoch: 7, Loss: 0.33609068393707275
 Epoch: 8, Loss: 0.3114171326160431
 Epoch: 9, Loss: 0.29162952303886414
 Epoch: 10, Loss: 0.2753564715385437
 Epoch: 11, Loss: 0.2617027461528778
 Epoch: 12, Loss: 0.25005775690078735
 Epoch: 13, Loss: 0.23998993635177612
 Epoch: 14, Loss: 0.2311851531267166
 Epoch: 15, Loss: 0.22340893745422363
 Epoch: 16, Loss: 0.21648260951042175
 Epoch: 17, Loss: 0.21026727557182312
 Epoch: 18, Loss: 0.2046533226966858
 Epoch: 19, Loss: 0.1995529681444168
 Epoch: 20, Loss: 0.19489510357379913
 Epoch: 21, Loss: 0.1906212717294693
 Epoch: 22, Loss: 0.18668316304683685
 Epoch: 23, Loss: 0.1830403208732605
 Epoch: 24, Loss: 0.1796586960554123
 Epoch: 25, Loss: 0.17650936543941498


In [82]:
model.linear.weight

Parameter containing:
tensor([[-0.2048, -0.2732, -0.1625, -0.4014, -0.0696, -0.1980, -0.3692, -0.2361,
         -0.1831,  0.1053, -0.1217, -0.0955, -0.0920, -0.1854, -0.0401,  0.1663,
          0.0173,  0.0794, -0.0593,  0.0474, -0.1735, -0.1356, -0.2895, -0.2670,
         -0.2794, -0.1522, -0.1105, -0.2410, -0.1673, -0.0539]],
       requires_grad=True)

In [83]:
model.linear.bias

Parameter containing:
tensor([0.1146], requires_grad=True)

In [84]:
x_train_tensor = x_train_tensor.float()
y_train_tensor = y_train_tensor.float()
x_test_tensor = x_test_tensor.float()
y_test_tensor = y_test_tensor.float()

# Evaluation

In [85]:
# model evaluation
with torch.no_grad():
  y_pred= model.forward(x_test_tensor)
  y_pred= (y_pred > 0.5).float()
  accuracy= (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5344721674919128
