<a href="https://colab.research.google.com/github/Madhavi-1234/pytorch-from-scratch/blob/main/Pytorch_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("GPU is avaiable!")
  print(f"Using GP U:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU.")

GPU is avaiable!
Using GPU:Tesla T4


# Creating a Tensor


In [ ]:
# USING empty

torch.empty(2,3)

tensor([[-1.7672e+36,  4.4742e-41,  1.3192e-20],
        [ 0.0000e+00, -4.9460e+23,  4.4741e-41]])

In [ ]:
# check type
a= torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,4)



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#using ones

torch.ones(3,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
#use of seed
torch.rand(3,5)


tensor([[0.2793, 0.1567, 0.8408, 0.0918, 0.1517],
        [0.3299, 0.1385, 0.8216, 0.4059, 0.9443],
        [0.6651, 0.3726, 0.6781, 0.4566, 0.0263]])

In [ ]:
#manual_seed
torch.manual_seed(200)
torch.rand(3,4)

tensor([[0.5939, 0.5008, 0.9961, 0.0311],
        [0.1716, 0.9481, 0.6470, 0.9265],
        [0.6200, 0.3349, 0.7323, 0.7349]])

In [ ]:
torch.manual_seed(200)
torch.rand(3,4)

tensor([[0.5939, 0.5008, 0.9961, 0.0311],
        [0.1716, 0.9481, 0.6470, 0.9265],
        [0.6200, 0.3349, 0.7323, 0.7349]])

In [ ]:
#using tensor
torch.tensor([[1,2,3,4],[5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
#other ways
#arange

print(f"using arange:{torch.arange(0,19,2)}")

using arange:tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [ ]:
#using linspace
#linearly spread value within the range
print(f"using linspace:{torch.linspace(0,10,10)}")

using linspace:tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
#using eye
#identity matrix
print(torch.eye(5))


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
#using full
print(torch.full((4,4),3))

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])


# Tensor Shapes


In [ ]:
x= torch.tensor([[1,2,3],[1,9,8,]])
x

tensor([[1, 2, 3],
        [1, 9, 8]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# tensor with same shape as X
torch.empty_like(x)

tensor([[132231527435648,       560308608, 132231424839328],
        [       11664576, 132231495328112, 132230903615792]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)    # Why error because rand do generate float values only  but

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

# Tensor Data Types



In [ ]:
#find the data type

x.dtype

torch.int64

In [ ]:
#assign data types
torch.tensor([[1,2,3],[2,3,4]],dtype=torch.float64)

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

In [ ]:
torch.tensor([[1.00,5.00,0.00],[1.22,3.55,6.00]],dtype=torch.int32)


tensor([[1, 5, 0],
        [1, 3, 6]], dtype=torch.int32)

In [ ]:
# using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [1., 9., 8.]], dtype=torch.float64)

# Mathematical Operations


In [ ]:
a=x+2
b=x-2
c=x*2
d=x/2
e=x%2
f=(x*100)//3   #int division
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

tensor([[ 3,  4,  5],
        [ 3, 11, 10]])
tensor([[-1,  0,  1],
        [-1,  7,  6]])
tensor([[ 2,  4,  6],
        [ 2, 18, 16]])
tensor([[0.5000, 1.0000, 1.5000],
        [0.5000, 4.5000, 4.0000]])
tensor([[1, 0, 1],
        [1, 1, 0]])
tensor([[ 33,  66, 100],
        [ 33, 300, 266]])


# Element wise operation


In [ ]:
a= torch.rand(2,3)
b= torch.rand(2,3)
print(a)
print(b)

tensor([[0.1324, 0.8810, 0.6145],
        [0.3696, 0.2307, 0.3122]])
tensor([[0.0692, 0.1695, 0.5716],
        [0.6428, 0.4965, 0.4156]])


In [ ]:
from binascii import b2a_base64
# add
p= a+b

# multiply
q= a*b

# division
r= a/b

# power
s= a**b

# mod
t= a%b

# floor division

u= a//b

print(p)
print(q)
print(r)
print(s)
print(t)
print(u)



tensor([[0.2016, 1.0505, 1.1861],
        [1.0125, 0.7272, 0.7278]])
tensor([[0.0092, 0.1493, 0.3513],
        [0.2376, 0.1145, 0.1298]])
tensor([[1.9129, 5.1967, 1.0750],
        [0.5750, 0.4647, 0.7512]])
tensor([[0.8694, 0.9787, 0.7570],
        [0.5274, 0.4828, 0.6164]])
tensor([[0.0632, 0.0333, 0.0429],
        [0.3696, 0.2307, 0.3122]])
tensor([[1., 5., 1.],
        [0., 0., 0.]])


In [ ]:
# absolute
c= torch.tensor([1,-2,-4,-5])
torch.abs(c)

tensor([1, 2, 4, 5])

In [ ]:
# hegative
torch.neg(c)

tensor([-1,  2,  4,  5])

In [ ]:
d= torch.tensor([[1.0,2.8,3.0],[1.6,3.0,2.1]])

# round
torch.round(d)

tensor([[1., 3., 3.],
        [2., 3., 2.]])

In [ ]:
# ceil
torch.ceil(d)

# floor

torch.floor(d)


tensor([[1., 2., 3.],
        [1., 3., 2.]])

In [ ]:
# clamp  (range)
torch.clamp(d, min=2, max=3)

tensor([[2.0000, 2.8000, 3.0000],
        [2.0000, 3.0000, 2.1000]])

Reduction operation


In [ ]:
e= torch.randint(size=(2,3), low=0, high=10,dtype=torch.float32)
e

tensor([[9., 7., 9.],
        [9., 8., 8.]])

In [ ]:
# sum
a=torch.sum(e)

# sum along columns
b= torch.sum(e, dim=0)

# sum along rows

c= torch.sum(e, dim=1)

print(a)
print(b)
print(c)


tensor(27)
tensor([ 9,  2, 16])
tensor([13, 14])


In [ ]:
# mean
a=torch.mean(e)

# mean along columns
b= torch.mean(e, dim=0)

# mena along rows
c= torch.mean(e, dim=1)

print(a)
print(b)
print(c)


tensor(8.3333)
tensor([9.0000, 7.5000, 8.5000])
tensor([8.3333, 8.3333])


In [ ]:
# median

a= torch.median(e)

#median along columns
b= torch.median(e, dim =0)

# median along rows
c= torch.median(e,dim=1)

print(a)
print(b)
print(c)

tensor(8.)
torch.return_types.median(
values=tensor([9., 7., 8.]),
indices=tensor([0, 0, 1]))
torch.return_types.median(
values=tensor([9., 8.]),
indices=tensor([0, 2]))


In [ ]:
# max and min
a=torch.max(e)
b= torch.min(e)

# max and min along columns and rows
c=torch.max(e,dim=0)
d=torch.min(e,dim=1)

print(a)
print(b)
print(c)
print(d)

tensor(9.)
tensor(7.)
torch.return_types.max(
values=tensor([9., 8., 9.]),
indices=tensor([0, 1, 0]))
torch.return_types.min(
values=tensor([7., 8.]),
indices=tensor([1, 1]))


In [ ]:
# product
print(torch.prod(e))
print(torch.prod(e,dim=0))
print(torch.prod(e,dim=1))

tensor(326592.)
tensor([81., 56., 72.])
tensor([567., 576.])


In [ ]:
# standard deviation and variance

#std..cols,rows

print(torch.std(e))
print(torch.std(e,dim=0))
print(torch.std(e,dim=1))


# variane..cols, rows.

print(torch.var(e))
print(torch.var(e,dim=0))
print(torch.var(e,dim=1))

tensor(0.8165)
tensor([0.0000, 0.7071, 0.7071])
tensor([1.1547, 0.5774])
tensor(0.6667)
tensor([0.0000, 0.5000, 0.5000])
tensor([1.3333, 0.3333])


In [ ]:
# argmax ( index position of the largest element)
print(torch.argmax(e))
print(torch.argmax(e,dim=0))
print(torch.argmax(e,dim=1))

tensor(0)
tensor([0, 1, 0])
tensor([0, 0])


In [ ]:
#argmin (index position of the smallest element)
print(torch.argmin(e))
print(torch.argmin(e,dim=0))
print(torch.argmin(e,dim=1))

tensor(1)
tensor([0, 0, 1])
tensor([1, 1])


# Matrix Operations


In [ ]:
f= torch.randint(size=(2,3),low=0,high=10)
g= torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[9, 9, 0],
        [2, 6, 2]])
tensor([[3, 5],
        [5, 6],
        [8, 0]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)


tensor([[104, 110],
        [ 49,  36]])

In [ ]:
# dot product
vec1= torch.tensor([1,2])
vec2= torch.tensor([5,4])

torch.dot(vec1,vec2)

tensor(13)

In [ ]:
# transpose
torch.transpose(f,0,1)



tensor([[9, 2],
        [9, 6],
        [0, 2]])

In [ ]:
h= torch.randint(size=(3,3), low=0, high=10, dtype= torch.float32)
h

tensor([[1., 8., 2.],
        [6., 9., 8.],
        [8., 1., 7.]])

In [ ]:
# determinant
torch.det(h)

tensor(99.)

# Comparison Operations

In [ ]:
i= torch.randint(size=(2,3), low=0, high=10)
j= torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6., 2., 9.],
        [2., 5., 4.]])
tensor([[2., 5., 0.],
        [9., 8., 1.]])


In [ ]:
print(i>j)
print(i<j)
print(i!=j)
print(i>=j)
print(i<=j)


tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False,  True, False],
        [ True, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False,  True, False],
        [ True, False, False]])


# Special Function

In [2]:
k=torch.randint(size=(2,3), low=0, high=10, dtype= torch.float32)
k


tensor([[6., 7., 9.],
        [0., 5., 3.]])

In [3]:
# log

torch.log(k)

tensor([[1.7918, 1.9459, 2.1972],
        [  -inf, 1.6094, 1.0986]])

In [4]:
# exp
torch.exp(k)

tensor([[4.0343e+02, 1.0966e+03, 8.1031e+03],
        [1.0000e+00, 1.4841e+02, 2.0086e+01]])

In [5]:
# softmax

torch.softmax(k,dim=0)

tensor([[0.9975, 0.8808, 0.9975],
        [0.0025, 0.1192, 0.0025]])

In [6]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9991, 0.9999],
        [0.5000, 0.9933, 0.9526]])

# Inplace operation

In [7]:
m= torch.rand(2,3)
n= torch.rand(2,3)

print(m)
print(n)

tensor([[0.1696, 0.4611, 0.3215],
        [0.6347, 0.8686, 0.9334]])
tensor([[0.7343, 0.8130, 0.4289],
        [0.4684, 0.3326, 0.9854]])


In [8]:
m.add_(n)   # changes(addition of m with n) will be saved in m

tensor([[0.9039, 1.2741, 0.7504],
        [1.1031, 1.2012, 1.9188]])

In [9]:
print(m)
print(n)

tensor([[0.9039, 1.2741, 0.7504],
        [1.1031, 1.2012, 1.9188]])
tensor([[0.7343, 0.8130, 0.4289],
        [0.4684, 0.3326, 0.9854]])


In [10]:
# permanent changes
torch.relu(m)

tensor([[0.9039, 1.2741, 0.7504],
        [1.1031, 1.2012, 1.9188]])

In [12]:
torch.relu_(m)

tensor([[0.9039, 1.2741, 0.7504],
        [1.1031, 1.2012, 1.9188]])

# Copying a Tensor

In [7]:
a= torch.rand(2,3)
a

tensor([[0.2091, 0.7022, 0.0236],
        [0.4220, 0.7119, 0.4967]])

In [7]:
b=a  # not a good approach   || if we will perform any changes in a it will be same for b but why when its just a copy right ???

In [5]:
id(a)


136937920632208

In [8]:
id(b)

136937920632208

In [9]:
#  to copy we use fn clone()

b= a.clone()

In [10]:
a

tensor([[0.5936, 0.9655, 0.6151],
        [0.0489, 0.2039, 0.7423]])

In [11]:
b

tensor([[0.5936, 0.9655, 0.6151],
        [0.0489, 0.2039, 0.7423]])

In [13]:
a[0][0]=19

In [14]:
b

tensor([[0.5936, 0.9655, 0.6151],
        [0.0489, 0.2039, 0.7423]])

In [15]:
a  # here the  changes will be saved only to the original not to the copy

tensor([[19.0000,  0.9655,  0.6151],
        [ 0.0489,  0.2039,  0.7423]])

# Tensor Operations on GPU

In [3]:
torch.cuda.is_available()

True

In [16]:
device=torch.device('cuda')

In [5]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3392, 0.1336, 0.0206],
        [0.8548, 0.2805, 0.7134]], device='cuda:0')

In [13]:
# moving an existing tensor on GPU
a
b= a.to(device)

In [10]:
b+5

tensor([[5.2091, 5.7022, 5.0236],
        [5.4220, 5.7119, 5.4967]], device='cuda:0')

In [18]:
# why we are using cpu and gpu .... when the ans and wokring is almost same right ??

# here's the answer:

import torch
import time

# check device
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# matrix size
size = 1000

# create CPU matrices
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# CPU timing
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time
print(f"Time on CPU: {cpu_time:.4f} seconds")

# move matrices to GPU (do this before timing)
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# GPU timing
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()  # wait for GPU to finish
gpu_time = time.time() - start_time
print(f"Time on GPU: {gpu_time:.4f} seconds")

# compare results (should be almost equal)
print("Difference:", torch.norm(result_cpu - result_gpu.cpu()).item())




Time on CPU: 0.0168 seconds
Time on GPU: 0.0010 seconds
Difference: 0.010979614220559597


# Reshaping Tensors

In [20]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [22]:
# flatten  (covert into 1 dimensional....)
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
b= torch.rand(2,3,4)
b

tensor([[[0.5539, 0.4347, 0.0178, 0.7854],
         [0.1788, 0.3976, 0.4351, 0.9938],
         [0.6895, 0.8521, 0.8159, 0.2246]],

        [[0.7544, 0.8982, 0.4278, 0.8235],
         [0.1358, 0.2816, 0.3823, 0.2853],
         [0.6241, 0.6773, 0.6033, 0.8240]]])

In [27]:
# permute.....( swap up the positioning)
b.permute(2,0,1).shape


torch.Size([4, 2, 3])

In [29]:
# unsqueeze
# image size
c= torch.rand(226,226,3)
c.unsqueeze(1).shape


torch.Size([226, 1, 226, 3])

In [33]:
d= torch.rand( 1,20)
d.squeeze(0).shape
d

tensor([[0.6229, 0.9334, 0.2752, 0.2177, 0.1672, 0.2771, 0.6935, 0.6858, 0.5999,
         0.6915, 0.5016, 0.3624, 0.7139, 0.0685, 0.9421, 0.3587, 0.3796, 0.8408,
         0.8213, 0.9280]])

# Numpy and PyTorch

In [2]:
import numpy as np


In [3]:
a= torch.tensor([1,2,3])
a


tensor([1, 2, 3])

In [4]:
b= a.numpy()

In [5]:
b

array([1, 2, 3])

In [6]:
type(b)

numpy.ndarray

In [7]:
c= np.array([1,2,3])
c

array([1, 2, 3])

In [8]:
torch.from_numpy(c)

tensor([1, 2, 3])

In [9]:
!git clone https://github.com/Madhavi-1234/pytorch-from-scratch.git


Cloning into 'pytorch-from-scratch'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.


In [10]:
!ls



pytorch-from-scratch  sample_data
